### ISSUE TITLE
Question: Is It posible to Redirect to Multiple Endpoints ?

### ISSUE THREAD

**Issue by hansbrito** [gildean/node-udp-proxy#10]
Hi! Is it posible to redirect messages to 2 distinct endpoints ?
I would like to replicate packets to multiple address.

Thanks in advance!

**Comment by gildean** [comment]
Hi! Currently that's not possible directly, but what you can do is create a wrapper that opens up a new udp socket and set up multiple proxies. Then send all the datagrams coming in to the new socket to all the created proxies inside your wrapper function.
