### ISSUE TITLE
no server answer

### ISSUE THREAD

**Issue by pdazcom** [gildean/node-udp-proxy#2]
Hi! request successfully reaches the server, but there no answer from end-server to client.

here is my code, it's just for example
client.php:

```
<?php
$fp = stream_socket_client("udp://X.X.2.166:11133", $errno, $errstr);

if ($fp)
{
        fwrite($fp, "TEST 1 TEST 2 TEST 3");
        $buf = fgets($fp);
        var_dump($buf);
        fclose($fp);
}
?>
```

server.php: (end-server script)

```
<?php
$socket = stream_socket_server("udp://X.X.2.166:11133", $errno, $errstr, STREAM_SERVER_BIND);
if (!$socket) {
    die("$errstr ($errno)");
    }

    do {
        $pkt = stream_socket_recvfrom($socket, 1500, 0, $peer);
        echo "$peer - $pkt\n";
        stream_socket_sendto($socket, date("D j M H:i:s Y"), 0, $peer);
    } while ($pkt !== false);

?>
```

i see "TEST 1 TEST 2 TEST 3" on server? but don't see date("D j M H:i:s Y") on client

in practice I redirects DNS traffic. DNS server is TinyDNS. In logs, I see that the requests reach the DNS server, but the answer is no.

**Comment by gildean** [comment]
Can't reproduce.
