### ISSUE TITLE
Reg:Error: Command failed:

### ISSUE THREAD

**Issue by priya23** [gildean/node-udp-proxy#6]
hi,
all my instances are running in amazon.i have set up my proxy on rhel machine which must send the data to  server listening on two port 8125 and 8126 respectively.Following are my changes to testIPV4.js

var options = {
    address: 'server1',
    port: 8125,
    ipv6: false,
    localaddress: 'privateip',
    localport: 5353,
    localipv6: false,
    proxyaddress: '127.0.0.1',
    timeOutTime: 10000
};
var mitmOptions = {
    address: 'server1',
    port: 8126,
    ipv6: false,
    localaddress: 'privateip',
    localport: 5354,
    localipv6: false,
    proxyaddress: '127.0.0.1',
    timeOutTime: 10000
};

when i am running node testIPV4.js its giving following error

25 Apr 11:35:02 -  \* IPv4 to IPv4  proxy \* | by : | ok:2012
25 Apr 11:35:02 -               running on | os : | linux
25 Apr 11:35:02 -    proxy-server ready on | IPv4 | privateip:5353
25 Apr 11:35:02 -  traffic is forwarded to | IPv4 | server1:8125
25 Apr 11:35:02 -            mitm ready on | IPv4 | privateip:5354
25 Apr 11:35:17 - Error: Command failed: 
25 Apr 11:35:17 - Error: Command failed: 

Can you help out for this error

**Comment by gildean** [comment]
Hi,
What are you actually trying to do? The ipv4test.js contains code to start two servers used to test one type of udp-traffic (namely dns) through multiple connections. In most cases you wouldn't need two servers to handle the proxying, one should be enough (look at the basic example on the readme).
